AWSRegion: "ca-central-1"
MongoDBHost: 192.168.86.137
MongoDBName: "gales-sales"
S3Bucket: ""
SsmPath: "gdps-fs-import"
Stage: "prod"
Dynamo:
  APIVersion: "2012-08-10"
  Region: "ca-central-1"
  Endpoint: "https://dynamodb.ca-central-1.amazonaws.com"
