AWSRegion: "ca-central-1"
CognitoClientID: "clientIDabc123"
CognitoPoolID: ""
CognitoRegion: ""
MongoDBUser: ""
MongoDBPassword: ""
MongoDBHost: 192.168.86.137
MongoDBName: "gales-sales"
S3Bucket: ""
SsmPath: "gsales-fs-export"
Stage: "prod"
Dynamo:
  APIVersion: "2012-08-10"
  Region: "ca-central-1"
  Endpoint: "https://dynamodb.ca-central-1.amazonaws.com"
